import type { Metadata } from "next";
import "@/styles/globals.css";
import { Bebas_Neue, Open_Sans } from "next/font/google";

const bebas = Bebas_Neue({
  variable: "--font-bebas",
  weight: "400",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bebas.variable} ${openSans.variable}`}>
      <body className="font-body text-text bg-surface">{children}</body>
    </html>
  );
}
